### ISSUE TITLE
Firefox Quantum Dark Theme - some additions?

### ISSUE THREAD

**Issue by BelladonnavGF** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#1]
Hi Izheil,

First of all, thanks for the chrome beautifications of the new Firefox 57 (Quantum)! I too missed my fully themed Firefox dearly (had [Stefano Rossellis brilliant FT Deepdark](http://stefrosselli.com/en/themes) before). Your code /collection certainly made Firefox more pleasing to (my) eyes again!

Trying to help making this better (since Moz obviously won't ☺), I think I might have some additions for you:
- When I put your .css to work and opened the bookmark menu on the toolbar (with the icon after the URL bar),  the standard "Bookmark menu" icon (star with space symbol underneath it) appeared where normally the standard arrow icon used to be. I solved this by adding this line to userChrome.css, removing the icon completely: `#BMB_bookmarksPopup .panel-arrow {display: none !important; }`
- In addition, the bookmark pull down menu had a think black border around it which also had a pretty big margin around it. To solve this I added:`#BMB_bookmarksPopup .popup-internal-box, .panel-arrowcontent {border-radius: 1px !important; margin: -.1em !important;}`
- I noticed that your code still keeps the tabs above the URL bar. I moved them (rather old fashioned, I know) to be placed below the URL bar with:`#TabsToolbar { -moz-box-ordinal-group: 10000 !important;}`
- Finally, and I know this is a personal preference, I defined the (mono) font of the URL bar text. This might be helpful to prevent URL spoofing (e.g. goog1e.com). For that, I added:`#urlbar { font-family: monospace !important;}`

BTW, I noticed that your code doesn't change the appearance of RSS pages. Did you run into something for that too by any chance? I tried it several times, but have been unsuccessful there ☹

Thanks again for sharing the code! I certainly helped me making Firefox more appealing (again)!

**Comment by Izheil** [comment]
Hello BelladonnavGF, 

Thank you for trying it!
I've been a bit busy trying to make the code a bit faster, but I've also fixed the issues you mentioned. 

- About the arrow problem you mentioned first, I tried to remove the .panel-arrows from most of the menus because of the same reason, but it ended up being an issue on the ones that did stay for the problem you mentioned. On this behalf, I've managed to find a way to color the arrows, so now they should all display accordingly, so we can tag that problem as **fixed**.
- About the bookmark menu problem... Since I've never used it through there (I use the personal bookmark toolbar below the url bar instead), I never realized that was happening. Gladly for those that do use it, now **it's fixed thanks to your report**!
- I personally like the tabs above the URL bar, which is why I didn't bother to add the code to change their position at first, but **I've added the lines to change their position** now for those that do like it that way. It will be commented out by default, so **you'll have to delete the commenting before those lines to use it**. (The reason for this is so that those that do install it for the first time and don't know or want to change the code in it won't find a completelly different browser after they do)
- The URL spoofing font change is also a nice addition, so **thank you for the suggestion**! **I added the line after the added features part** just like the other one. I decided to use "georgia" as default font for the url, since I think it can be told easier the differenciate between numbers and letter than monospace (since georgia makes numbers be smaller, or have more padding on the upper part of the symbol), but feel free to change that back to monospace if you find it more fitting in your case.

I haven't used RSS, but for what I saw they should just be like regular pages?
This theme is mainly focused to change the layout of the "off-limits" pages for extensions (aka about: pages, or firefox UI), but for other pages you can use [stylus](https://addons.mozilla.org/es/firefox/addon/styl-us/).

After you have installed stylus, you can download user-made styles for individual pages.
An example would be [this](https://userstyles.org/styles/84836/dark-night-feedly-wide-condensed), but if that's not what you were looking for, you can still check for other ones in that page.
