### ISSUE TITLE
Change the color of the text on the Bookmarks toolbar 

### ISSUE THREAD

**Issue by tungmilan** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#10]
Hello,

Thank you so much for developing this. I enjoy using it so far.!

However the text on the bookmarks toolbar is black which doesn't work well with the dark theme. 

![capture](https://user-images.githubusercontent.com/6590141/40136706-593a99c4-58fd-11e8-910c-738123545e9c.PNG)

Can you tell me how to change its color to be the same as the rest? 

Thanks!

**Comment by tungmilan** [comment]
Found the fix myself by adding the following lines to `userChrome.css` 

```
.bookmark-item {
  color: #eee8d5 !important;
}
```

**Comment by Izheil** [comment]
Sorry for the late reply (since you already solved it), just wanted to add that this is changed by the persona you are using, so the way intended was changing it through about:config on the lightweightThemes.usedThemes setting. I guess I should clarify that in the description, but thanks anyway for noting it!

**Comment by tungmilan** [comment]
@Izheil : thank you for the tip! Is there a simple way to switch to normal theme without breaking everything? I tested normal theme but then all the text wasn't visible anymore

**Comment by Izheil** [comment]
The default theme uses the colors from your OS theme, which is why it appears with black letters and icons for you. 
I updated <code>userchrome.css</code> so that now you can change the text and icons color through there using the <code>--bookmark-toolbar-text</code> and <code>--nav-bar-icons-color</code> variables respectively.
This way it will be easier to change it no matter the theme you use!

**Comment by tungmilan** [comment]
Great! Let me try it out. Thanks!

**Comment by tungmilan** [comment]
@Izheil : how can you change the color of the text inside the search box on Youtube? I'm using Firefox Billboard theme & Youtube Dark theme, the text inside the search box is black which basically makes it invisible. Thanks!

**Comment by Izheil** [comment]
Input boxes get their text color from the variable <code>--text-color-for-input-fields</code> inside usercontent, so changing "none" to #fff or #ccc would make the text visible. (#ccc would stand for a neutral gray that can be seen in both black and white backgrounds, while #fff would be white)

**Comment by tungmilan** [comment]
`#ccc` is not really good on white background (e.g. here on GitHub). I found that `gray50` or `#7f7f7f` works the best for both black and white backgrounds   

http://www.color-hex.com/color/7f7f7f  

Thanks!

**Comment by Izheil** [comment]
Ah, you are right. I don't know why I thought #ccc was the good one.
I'll change it on the description, thanks!
