### ISSUE TITLE
Tab drag and drop doesn't work

### ISSUE THREAD

**Issue by tungmilan** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#11]
Hello,

I notice that when I have multi-row tabs, I can't drag and drop the tab to the place that I want especially between rows.

Is there any setting that I missed?

Thanks!

**Comment by Izheil** [comment]
No, sadly that's an issue that can't be solved (It's in the FAQ) due to a firefox bug, so all possible CSS solutions to this can't fix it.
The issue will only appear when you have more than 1 row. You can, although, disable multi-row meanwhile if you don't want it.
I've been trying to find a fix to this, but looks like everyone using multi-row tabs through CSS has the same problem (no matter how you make multi-row appear), so as of right now, it's either tabs in moving line (default firefox), or unmovable multi-row tabs.

**Comment by tungmilan** [comment]
Thanks for the info! It's not too bad so I can still live with it

**Comment by tungmilan** [comment]
@Izheil : that's great. Can you show me which lines in userchrome to delete after copying the *.js file into chrome folder? Thx

**Comment by Izheil** [comment]
Should be the lines from <a href="https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/commit/9fc9da794dda3052d1acebce27f24f64795818b2#diff-f653561dd2f258dc4a1dd1fee5731323">this</a> commit.

**Comment by Izheil** [comment]
You can now get the scrollable versions from the repository (inside the "Multirow scrollable versions" folder inside "Scrollbars & tooltips dark theme")

**Comment by Onepamopa** [comment]
Let me correct my question - mouse-scrollable.

**Comment by Izheil** [comment]
Nope, not possible that I know of, sorry.
