### ISSUE TITLE
[Solved] FF 60.0.2 Can't get scrollbars to work

### ISSUE THREAD

**Issue by snwflake** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#12]
```
.../chrome
    ├── scrollbars-minimal.uc.js
    ├── tooltips.uc.js
    ├── userChrome.js
    └── userContent.css
```

Root files also in place at `/Applications/Firefox.app/Contents/Resources/`.

FF Version: `60.0.2 (64-bit)`
MacOS: `10.12.6`

Tried starting with `--headless`, hoping some error would pop up -> negative.
I don't have any experience with FF apis, so no clue where to start debugging...

Edit: Cache cleared, obviously.

**Comment by Izheil** [comment]
Ah, my mistake, I forgot to update the root files locations since the legacy method.
I don't have a Mac to test it, but the root folder should be in<code>/Applications/Firefox.app/Contents/</code>. 
Make sure that there is a "defaults" folder inside the contents one, (which is where you'd have to paste the contents of that folder, of course) and that config.js and userChromeJS.js are inside the folder where Firefox's binary file is located. (the .dmg file on Mac I think)
Tell me if you found the right folder and I'll update the descriptions in the repository!

**Comment by snwflake** [comment]
Perfect!

I'll submit a PR for the doc changes in about an hour ;)

**Comment by snwflake** [comment]
#13 created :)

**Comment by Izheil** [comment]
Thanks for the updated paths for Mac!
I'm glad you could make it work.

**Comment by snwflake** [comment]
You're welcome!
And thanks for your work!
