### ISSUE TITLE
Certain Context Menu elements missing

### ISSUE THREAD

**Issue by Icarus77** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#16]
Hello, I've used this theme for months and updated it only a couple of days ago after a Firefox update reverted the scrollbar and made the address bar white again. After installing, I came to notice that the context menu was missing certain elements that I really miss. I've made an image comparing the menu when I click on a video thumbnail in Firefox without the theme (safe mode) vs Firefox with your theme.

http://puu.sh/AUgEQ/2ad736fd70.jpg

**Comment by Izheil** [comment]
There are 2 versions of the theme, the "full" one, and the "only colors" one. 
The full one adds some more functions like hiding some context menu commands that aren't used often, as well as always showing the close button on tabs, or changing the font of the url bar.

If you don't want any of those things, you should use the files inside the "theme colors" folder.

If you want to hide certain commands but not all, you can use the full theme, but delete or comment out the commands you want to keep (inside userchrome.css, past the /* CONTEXT MENU COMMANDS */ line). Just make sure to encase the selector between /* and */ to comment it so that it's shown again.

Example: 
<pre>/* Open link in a new tab */
#context-openlinkintab,</pre>

would turn into:

<pre>/* Open link in a new tab *//*
#context-openlinkintab,*/</pre>

You can tell which ones are already commented out because they will have the starting /* right after the comment that explains what they hide (They just use the start of the next comment as the closing tag).

Alternativelly you can just delete all selectors past the /* CONTEXT MENU COMMANDS */ line, so that it shows all things as it would by default.

**Comment by Icarus77** [comment]
Thanks. Another thing is that the text box for youtube's dark theme seems to just stay black, making it impossible to see unless highlighted
http://puu.sh/AUinS/a7f9107dc4.png

**Comment by Izheil** [comment]
Thanks for noting the issue!
I changed the color of input boxes to neutral gray, so either update, or change the variable <code>--text-color-for-input-fields</code> to #777 instead of none inside usercontent.css.
You can see the change <a href="https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/commit/42cb36ef9e4388e3f8433369d68637bf5457cb6b">here</a>.

**Comment by Icarus77** [comment]
Now the text for all input boxes like Github is grey when it was formerly white. In the past, search boxes like youtube or google and bing had blue text, but normal input boxes like Github were still white. 

How can I get it back to this way?

**Comment by Izheil** [comment]
The input boxes color change always affected all, unless the site had an "!important" rule in their CSS that would overwrite the one I put on usercontent.

<a href="https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/commit/7e1ce41455d895020385fe3f3abaa42e958a1e2a">I disabled the input boxes color change altogether now</a>, since it was only suposed to be a fix for those people who had a dark OS theme that would get some input boxes text black over black background... but it seems to cause more issues with those that don't have one.

Comment out the rules I changed in that commit, or delete them so that it shows the colors it should by default.

If you want blue text, just change the variable to #2066dd instead, but it will change all text colors, it was never suposed to change only a few pages.
