### ISSUE TITLE
Scrollbars position not quite right

### ISSUE THREAD

**Issue by tungmilan** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#17]
Hello,

I'm using this one on Firefox 61.0.1 / Win 10 Pro
https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/tree/master/Scrollbars%20%26%20tooltips%20dark%20theme

I noticed that the scrollbars weren't placed correctly when viewing attached files (PDF) in Gmail

![snap_00076](https://user-images.githubusercontent.com/6590141/42961735-8f956ca0-8b44-11e8-8935-1b36d84b4284.png)

How can I fix this?

Thanks!

**Comment by Izheil** [comment]
Thanks for noting the issue!
I think the problem is caused by the z-index of the scrollbars, which made the scrollbars to always be shown on top, making the scrollbars from below the previewing layer appear over it.

You only have to <a href="https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/commit/e6ce082709609cf65ebe837e98bd355c7566ab8f">delete the z-index and position attributes</a> from the scrollbars*.uc.js file you are using and the startup cache for changes to take effect (open about:profiles, then choose the local profile folder, then delete anything inside the "startupcache" one), and then it should be solved.

**Comment by tungmilan** [comment]
That did it. Thank you!
