### ISSUE TITLE
Directory "startupCache" is no longer in the profile directory on Mac

### ISSUE THREAD

**Issue by geek-zero** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#19]
Saw this in 61.0.2

So what do I delete now to get changes to the js files to be picked up?

**Comment by Izheil** [comment]
The directory should still exist, make sure you are in the right profiles folder.

There are 2 profile folders, which you can access in <code>about:profiles</code>:
<ul>
  <li>The "root folder" one, which should be in <code>~/Library/Application Support/Firefox/</code></li>
  <li>The "local folder" one, which should be in <code>~/Library/Caches/Firefox/Profiles/</code></li>
</ul>

The "root" profile folder is the one where you place the chrome folder.
The "local" profile folder is where the startupcache should be.

The safest way to find it would be through the <code>about:profiles</code> page instead of navigating to it.

**Comment by geek-zero** [comment]
Yep went to about:profiles, both on a new machine and one I jumped into your code with on 60.  The greenfield machine, the ~/Library/Caches/Firefox/Profiles directory is empty.  I saw no sign of the startupCache on the upgraded machine when doing the about:profiles, though last week I know it was there.  I'm thinking there's been a directory move from the Mozilla folks perhaps?

**Comment by Izheil** [comment]
Could be, kind of odd that they would only do that for Mac, since it's still here on Windows.

Another possible way to find it would be locating the new cache folders location directly through <code>about:cache</code>, look for the path on the "disk" section, and go down 1 folder from the cache2 to where the other cache folders are.

Tell me if you find it and I'll update it here.

**Comment by Izheil** [comment]
No problem, glad you could solve it! 

I'll close this now.
