### ISSUE TITLE
Linux Debian Conundrums

### ISSUE THREAD

**Issue by DebSec** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#23]
Izheil,

O/S Debian 9.5 Firefox ESR 60.2.2 64bit

1. The Mozilla add-on pages and others are not colored.

2. The sub menu's expand and contract.

3. Clear Recent History is not colorized.

Screenshot:
https://imgur.com/a/oXx6Fzy

userChrome.css (colors):

https://gist.github.com/DebSec/05cf9c960203de391c11861fd7832ef3

useContent.css:

https://gist.github.com/DebSec/b561633bc0499c0c4ec716f9119a0ea1

**Comment by Izheil** [comment]
1. You are missing a closing } on line 558, which makes all the things beneath it not apply at all. 
2. The padding of those menus (at least the height of each row) is set for the default windows font, since debian firefox inherits the font of your OS, that is bound to change. The padding to the left is not something specified on this usercontent, so, again, it's something related to Debian. Add some padding-left pixels on the menuitem:hover selector inside the (about:) context menus section on usercontent until it's aligned, and some padding-bottom or padding-top on menuitem until you see the rows not changing height.
3. I just added the theming for the sanitizer window (Clear recent history/data), you can see the changes [here](https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/commit/cf6e9212cbf937f1950d34ce7c02428adff7f14f).

**Comment by DebSec** [comment]
Izheil,
Thanks for the direction.
1. On line 558 useContent.css I had seen the extra } when comparing our files. I thought you had an extra one. That did correct the issue with Mozilla not being themed correctly.

2. On the menu hover I had to remove some of your code for the padding to correct itself.
-moz-appearance: none !important; was the culprit for some reason.

useContent.css:
`/* This changes the text of disabled items */
menuitem[disabled="true"],
menu[disabled="true"] {color: #777 !important}
	
/* This changes the color on hover of the context-menu items */
#context-navigation menuitem:hover {
  background: var(--in-content-context-highlight)!important
}

#context-navigation menuitem:hover[disabled=true] {
  background-color:  #333 !important
}

menuitem:hover,
menu:hover {
	background-color: var(--in-content-context-highlight) !important} 

/* This does the same but for disabled ones */
menuitem:hover[disabled="true"],
menu:hover[disabled="true"] {
	background-color: #333 !important}
`

3. The Clear Recent History box is the correct colors now. The drop down box could use some work in that area as someone who did not know that there was one there would not know to click on it as the drop down arrow seems to have blended away for me. But it works.


Screenshot:
https://imgur.com/a/2WMZDbw

**Comment by Izheil** [comment]
You can use the <code>checkboxes.as.css</code> file to turn all select-like items and checkboxes to a better version on white-background OS's.
You will have to <a href="">delete the dialog menulist elements from userchrome first</a>, and then create a new rule on userchrome if you don't want to use the <code>checkboxes.as.css</code> file, or are only interested on the select elements:
<pre>dialog menulist, menulist {
  filter: invert(81%) hue-rotate(170deg) !important; color: #000 !important}</pre>

**Comment by DebSec** [comment]
I removed the code in your notes and added what was needed in userChrome.css for the highlighting of the check boxes. I then called the @import url(./config/checkboxes.css); in using userChrome.css. That worked for the sanitizer window check-boxes.

I did not have any bright highlighting of the check-boxes in the #main-menubar and right clicking on the main bars gave no highlighted check-boxes and such. I added this to your checkboxes.as.css but now I have an issue with bookmarks and it's brightness for hovering over bookmarks and the icons are inverted.

/* Same for select (dropdown) elements */
dialog menulist, menulist, **menuitem,** listitem[type="checkbox"], dialog select {
  filter: invert(81%) hue-rotate(170deg) !important; color: #000 !important}

**Comment by DebSec** [comment]
I have added a .gif for you to view what I'm talking about. The colors of the check-boxes is correct now but the blue highlighting over the links is distracting. It would be great to have no highlighting of anything but the text when hovered to a brighter color.?

https://imgur.com/a/AmUrwEw

**Comment by Izheil** [comment]
<code>.menu-iconic-left[checked="true"]</code> should have at least changed the ticked checkboxes on the menus, but if that wasn't the case, you can just use a more general rule instead that will affect anything inside the menuitem with checkboxes that isn't the text nor the background color:

<code>menuitem[type="checkbox"] *:not(label)</code>

**Comment by DebSec** [comment]
I changed things a little. The code you provided me I added to the tooltips.css with a note. Your code works for the sanitizer window check-boxes. Sadly it has no affect elsewhere in the browser.
`/* Fix for OS's (like default windows) that draws checkboxes and radio buttons whiteish */
dialog menulist, menulist, menuitem[type="checkbox"] *:not(label) {
  filter: invert(81%) hue-rotate(170deg) !important; color: #000 !important}`

I also tried to enter other variables or narrow it down as you had e.g. menuitem[type="checkbox"] or menu-text and others with no luck.

We now know it works with just menuitem. Wish we could narrow it down to the specific areas. When using menuitem alone with this code:

`/* Fix for OS's (like default windows) that draws checkboxes and radio buttons whiteish */
dialog menulist, menulist, menuitem {
  filter: invert(81%) hue-rotate(170deg) !important; color: #000 !important}`

I get this change for the colors on hover and I can't find a happy medium.

Screeny:
https://imgur.com/a/rLmYpJL

**Comment by Izheil** [comment]
It might be a difference on the selectors for the ESR version, since for me the only things inside menuitem with checkboxes that contain the checkboxes are those selectors I told you previously. 

Try checking the selectors on your end, it will be faster than me trying to guess them. To do so, press F12, then F1, or just open the developers tools, then go to settings (pressing the 3 dots button on the top right part of them, next to the close button), then make sure you have checked the following things under advanced settings:
<ul> 
  <li>Enable remote debugging</li>
  <li>Enable browser chrome and add-on debugging toolboxes</li>
</ul>
After that, close the developer's tools, and press <code>ctrl</code> + <code>alt</code> + <code>shift</code> + <code>i</code>, and the browser debugging toolbox will open.
It will ask you if you want to activate remote debugging (from your own adress, so you don't have to worry about that), accept, and then you will be able to check for the selectors on your browser.

When checking for the selectors on a popup (like the title bar ones we want to check), make sure you click the 3 dots on the browser debugging's tools, and choose the option "disable popup autohide".

Sometimes this toolbar may glitch and when you hover over a popup items it will NOT let you see them (an empty line will appear on the toolbox inspector). If this happens, just close the toolbox, and reopen it.

**Comment by DebSec** [comment]
I have used the developers tools all along. Thanks I knew about the button to keep sub-menus open while picking sub-sections. I have spent allot of time on it with no luck. menuitem was the only selection that I could find that worked to color the check-boxes and radio buttons as I had shown.

For now I removed menuitem from the pertinent code and will have dark selectors in a couple areas. I do prefer having the text highlight when hovered like I have it now.
If you come across anything please let me know. Thanks for the efforts. I'm glad the sanitizer window and the clear recent history box is working good now.

**Comment by Izheil** [comment]
Well, at least the most important parts are still dark. It's still weird that the other selectors didn't work.

Usually for checkboxes on firefox you'd have to color the ::before on their label, as in label::before, so you could try:

<code>menuitem label::before</code>

That's the only thing I can think of that could work right now, otherwise I'm at a loss, but I guess that must be some difference between ESR firefox and quantum.

**Comment by DebSec** [comment]
The code that you asked me to try did not change the elements. I did however make good progress. Looking over what we had and trying to narrow it down I basically rested what you had in the code but specifically for the menuitem and everything works for the most part very well. I still have the parents (?) of some elements turning blue when I hover over there background. I would like those to have no background either. 

https://imgur.com/a/UCWvCtw

`/* Fix for OS's (like default windows) that draws checkboxes and radio buttons whiteish ", menuitem"*/
dialog checkbox .checkbox-check, dialog radio .radio-check, toolbar[printpreview="true"] checkbox:not(label),
dialog menulist, menulist, menuitem[type="checkbox"], menuitem[type="radio"], listitem[type="checkbox"], dialog select {
  filter: invert(81%) hue-rotate(170deg) !important;
  color: #000 !important}`

**Comment by Izheil** [comment]
You could always add a specific rule for the menuitem elements you added. Something like:

<pre>
menuitem[type="checkbox"], menuitem[type="radio"] {
  background: transparent !important;
  color: #000 !important;
  filter: invert(81%)}
</pre>

That way you can just apply the inversion filter for those 2 items, while also making sure that they get a transparent background.

Hmm... still, I feel like finding the actual selector for it would be easier.
Something like <code>menuitem > *<code> should color both the text and the checkbox without affecting the background (and since in the code we already color the texts black so that it gets inverted to grey... that shouldn't be an issue.

**Comment by DebSec** [comment]
I had no success with the code. Looking over what is presently used for code it could be perhaps something I need to over-ride from my O/S theme as moving around folders and doing various tasks in menus on my O/S I have the blue highlight when moving over certain things and also when there selected.

  -moz-appearance: none !important; I believe is used to apply the OS's theme.

**Comment by DebSec** [comment]
No luck with the code you suggested. I did minimize a little of it . This is the minimum code to make this work for me. If I use the rest of your code the Clear Recent History Box background is faded.

`/* Fix for OS's (like default windows) that draws checkboxes and radio buttons whiteish */ 
menuitem[type="checkbox"], menuitem[type="radio"] {
  color: #000 !important;
  filter: invert(81%)}`

When looking at this image you will eventually notice the text next to the check-boxes in the Clear Recent History Box are dimmed using the previous code.
https://imgur.com/a/UCWvCtw

Now with this code the Clear Recent History Box text is better. We are manipulating the box highlight as it has changed from _blue._
https://imgur.com/a/gKgfcRX

********************************************************************************************
I think I will set this aside as the bookmarks are highlighted blue and there is a issue with the userContent.css.
When you look at the image the drop down box in about:addons the checkbox is dark there. Also the text in the button ?tooltips? and other areas in there is missing. Look at the .gif and you will get what I'm after. Thanks

**Comment by Izheil** [comment]
This looks like a pretty specific bug that you are having and of your specific distribution, and since you have some more code than the one from this theme, I can't even know if it's something from this or a mixture of other things you may have, so I really can't help you more, sorry.
