### ISSUE TITLE
List All Tabs not working, Customize page going white, requesting 3 addons

### ISSUE THREAD

**Issue by Allrick1** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#24]
First of all I want to say I love this theme, and please don't stop supporting it!  I love the Theme colors, scroll bars, and added features.  The only thing I don't use is the multi-row tabs.

The List All Tabs drop down menu on the far right hand side top part of the tab bar doesn't work.  The only way I can scroll through multiple tabs is using ctrl+tab.  I am using the full dark theme on Mac OS Mojave.  I also use the browser's default dark theme.

I also notice the customize page is white background when I fresh start the browser, but after I choose dark theme it will stay dark until I close it and open it again.  Then it is white again.

There are 3 add-ons I would love you to add support to:
Notifier for Gmail - I get some coloring using other add-on settings in addons.css
Ad Block Plus - I get some coloring using other add-on settings in addons.css
HTTPS Everywhere - I get some coloring using other add-on settings in addons.css

I also use your Privacy Badger and LastPass setting in addons.css

Thanks so much for an awesome Dark Theme.  Keep up the awesome work!

**Comment by Izheil** [comment]
Thank you for using the theme!

The reason why the List All Tabs button wasn't working is because of the binding we used on the .xml file was made related to the menu of that button, but I updated it so that now it's fixed. 

The customize page issue... I made a better fix so that now it applies to all themes in use (except the default one), so it shouldn't be an issue anymore now.

You can see the changes [here](https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/commit/e5eec1f39c9ee90de7d0677d0cd48d2392280f86?diff=unified).

I would be okay with theming Notifier for Gmail and HTTPS Everywhere, but as for Ad Block Plus, I already have a theme for a better less CPU demanding adblocker (Ublock Origin) that even blocks more ads, so theming adblock plus would kind of be in some way saying that I'd be okay with people using that, which isn't really the case.

That's not to say that I would never do a theme for it, but I just don't see much reason for it, more than it being more popular because it came out before ublock origin, or because people who are more used to adblock are reticent to switching to Ublock origin.

**Comment by Allrick1** [comment]
Thanks for your quick response, with the changes!

I appreciate your opinion on Ad Blocker Plus.  I should go back to Ublock Origin then.  I was using it, but it does so much more then I could understand.  I have a bit of a learning curve with it.

Thanks for looking at the other 2 addons!

**Comment by Allrick1** [comment]
How about OneTab?

**Comment by Izheil** [comment]
I themed both OneTab and HTTPS Notifier, you can see the relevant code [here](https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/commit/1b718c99957ab2bf34246a20f1467b10ef2f263b).

As for Notifier for Gmail, do you mean [this one](https://addons.mozilla.org/es/firefox/addon/notifier_for_gmail/)? (Just making sure, since it has very few users, and there are a few notifiers for gmail out there for what I can see)

**Comment by Allrick1** [comment]
Notifier for Gmail is this one: [https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless/](url)

**Comment by Allrick1** [comment]
The OneTab and HTTPS Everywhere are perfect!

I have one other area that doesn't look right in the addons page where you can click the menu to update addons, and the search bar there if you right click the search area, they don't have the right background.  See photos: https://imgur.com/a/ZP1zgHa

**Comment by Izheil** [comment]
Finished the theming of notifier for Gmail, you can check the relevant code [here](https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/commit/06f0bf9be42b0c45b58c9bfa54026e868aefce24).

**Comment by Allrick1** [comment]
Thanks again!  Love it!
