### ISSUE TITLE
Editing chrome.manifest = crash

### ISSUE THREAD

**Issue by Icarus77** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#3]
I edited my chrome.manifest file with the single line required to be able to modify the scrollbar, and the browser just crashes repeatedly until I undo my modification and make it blank again. I am using Firefox 57 on Windows 7, so I don't know what could be the issue.

Also, how do I change the color of text boxes?  On certain sites, the grey text box clashes with the black text that the site enforces, making it hard to read.

**Comment by Izheil** [comment]
First of all, thanks for trying the theme!

Now, about the problems... 
The crash shouldn't happen, undepending on the windows version (I've tested it on w10 and w8, but I'm quite sure it shouldn't be an issue on w7, since it's not a windows dependent thing). Make sure that after editting the chrome.manifest on firefox root folder (should be "C:\Program Files\Mozilla Firefox" or "C:\Program Files (x86)\Mozilla Firefox" depending on if you have the 32 or 64 bits firefox) you place the "scrollbars.css" file without any modification to the original part (the one that comes before the new scrollbar) in the same folder.

If you used the search box on windows to find it, you may have found the second chrome.manifest file that is inside "C:\Program Files\Mozilla Firefox\browser", which is **NOT** the one you have to edit, so ignore that one.

If for some reason it keeps crashing, check for typos (maybe you forgot the last -s of "scrollbars.css" on the line, it happened to me some other times before). 

The line should be : "override chrome://global/skin/scrollbars.css scrollbars.css" with no quotation marks.
There shouldn't be any spaces before or after that line either (don't think spaces would be a problem... but just in case)

Also, this should be obvious, but im saying it just to cover all possibilities, **do NOT edit any of these files with Word**, or any other enriched text editor,  use notepad or any other code editor (such as notepad++ or sublime text) for this. The reason for this is that if you edit any of the files with Word or alike programs, some lines will be added to the file apart from the one that you edited, which you won't be able to see, and will make the file crash your firefox.

If it still crashes with that, try pasting the chrome.manifest file I uploaded here, which i copied directly from my own folder (you can check it to see that only that line is present), and tell me if that works, if it still doesn't I'll look further into it.

About the text box issues, I'm not sure about the reason, since this theme doesn't affect text boxes, so they should still show as they are by default (white background and black letters), but I'll add that fix on line 29-38 of usercontent for those that have the same issue. The possible reason this might be happening is because you may be using some userstyle with stylus, a windows theme, or some other extension that affects web pages (it happens the same to me on the search boxes on some webs when using a Windows theme, but oddly not on text boxes)

You can test this checking this page: 

https://www.w3schools.com/html/tryit.asp?filename=tryhtml_elem_textarea_style

If it shows a white textarea with black letters and you aren't using a windows theme, that should mean that there is nothing else affecting your firefox, so it's either a problem with the specific page you found this glitch, or some userstyle that you may be using. In case it shows a non-white background text box, that means that there is something else (either a windows theme, which you should have turned back to windows default theme for this test, so that shouldn't be the case, or a global theme or an extension) affecting your pages.

If you don't want to use the usercontent provided here, you can still change the text box letters color to a neutral blue (So that you can see it on both white and black background) creating a usercontent.css file, and adding the lines:

@-moz-document url-prefix(http){ 

textarea {color: #2066dd !important}

^ This will change the textarea (text boxes) letter colors to a neutral dark blue. You can always try some range of neutral gray, but it will be seen worse (I've tried before on search boxes) on white backgrounds.

If you only want it for certain pages, you can always specify the exact page on the url-prefix part of the code from above:

@-moz-document url-prefix(http://(The starting common part of the problematic page){

example:

@-moz-document url-prefix(http://github.com){

^ This would affect all pages which start with http://github.com, which would include this one.

**Comment by Icarus77** [comment]
Found out the problem. I put the scrollbars.css into the chrome folder with the other .css files instead of into the root of Firefox.exe's folder. The dark text box fixed itself upon restarting Firefox as well, so I guess all is well. 

On another note, I am curious [about the color for filling in forms/search bars](http://puu.sh/ywpJl/ce67100acd.png). It is a purple/indigo color that just happens to be very similar to the custom highlight color I set for my Windows theme. So I am wondering if that's just a coincidental color choice that you chose, or if that color actually changes depending on your windows highlight colors. IF you could tell me how to change that back to black or white just in case I ever change my Windows theme, but want to keep the dark FF theme, I'd appreciate it.

I'm referring to this:

**Comment by Izheil** [comment]
Glad to see that the main issues are gone!

The color of the letters of the search bars is just a color I chose for fitting on both black and white backgrounds (that way both the ones that saw a dark background (aka the ones with a dark windows theme) and the ones that see a white background on those forms can see the letters correctly), so it's not tied to the highlight color of your windows theme (that could cause problems if you had dark highlights with the dark backgrounds).

You can easily change the letters back to normal editting the lines 35 to 38 of the usercontent file in here.
If you want to keep the lines (just in case you think that you may use them later on), you can avoid them from being read "commenting" them.

To comment some lines that you don't want to be read, just encase the code lines between /* and */

Example:

/* This line won't be read */
/* You can make as many line breaks here as you want, enter code here, or anything
like this

textarea {
  color: red
}

^ This would normally turn the letters on the textareas red, but it won't in this case, since
it's still in the space between the asterisks and bars.

Nothing will be read until the next ending part of the comment is found , aka this -> */

If you only want a certain class between those lines to not apply (for example, you don't want the search box letters to be blueish, but want all the others to be), you can encase the class between the commenting symbols as well. Just make sure that there is NEVER a comma BEFORE the starting bracket

Example:
(So let's say you wanted to get rid of ONLY the search box letter custom coloring)

textarea, input[type=text], input[type=password], /* input[type=search] */ {
  color: blue !important
}

^ This would be WRONG, since it will be read as: 

textarea, input[type=text], input[type=password], {
  color: blue !important
}

^ That comma will make all the rule invalid, not accounting any of the previous things.
The correct way would be: 

textarea, input[type=text], input[type=password]/*,  input[type=search] */ {
  color: blue !important
}

^ It doesn't matter if the /* doesn't have spaces before or after the text, it will be recognized midsentence if needed, and won't stop avoiding to read until the next */ is found.

Now, back on topic with the last question, you should see what most of the rules on userchrome do with the explanations I put as comments before each rule saying what each does, but I understand there can be some confusion on some of them.

The line you are looking for is line 19, which would be this rule:

/* This root class will modify the colors of toolbar background color (by default is transparent white 
without this change) */
:root:-moz-lwtheme {
--toolbar-bgcolor: rgba(0,0,0,.6) !important;

^ what you have to change is the rgba values. (RGBA stands for Red, Green, Blue, Alpha)
You can choose any color you want for the toolbar background color, it will be applied to the tabs as well.

You can choose a color easier using some image editor program, like paint, and choosing the color palette there to find a color and it's RGB values.

The Alpha value (the .6 in the code) is the transparency, being 1 not transparent at all, and 0 completelly transparent. 

If you don't want the tabs to be whitish nor dark, you can set the alpha value to 0.

If you want the tabs to be whitish, change the rgba value to rgba(255,255,255,.6), etc...

On another note, I've noticed that you are using a persona with a black tab line (making it even harder to see the active tab), so you may want to change the tab line color instead of the tabs color (or you can change both, of course!).

There is a css code to change it, but I decided to not force a tab line color, and instead let people use their persona default one. Even with this, there is still a way to change the tab color without changing userchrome.

Enter the page "about:config", click the "I accept the risk" button, and search "lightweightThemes.usedThemes". After you find that entry, right click and modify it. 

It should let you change the tab line value (the colored line above the active tab, making it easy to tell which one is it), and the toolbar text color.

Once you click the modify option, a popup window will open, and will have some information about your currently installed personas. (the first one is the one you are using currently)

Example:

[{"id":"275698","name":"Deep Dark Blue Forest","headerURL":"https://addons.cdn.mozilla.net/user-media/addons/275698/h_darkforest.jpg?1295662891","footerURL":"https://addons.cdn.mozilla.net/user-media/addons/275698/f_darkforest.jpg?1295662891",**"textcolor":"#ffffff","accentcolor":"#0084ff"**,"iconURL":"https://addons.cdn.mozilla.net/user-media/addons/275698/preview_small.jpg?1295662891","previewURL":"https://addons.cdn.mozilla.net/user-media/addons/275698/preview.jpg?1295662891","author":"EatingStick","updateURL":"https://versioncheck.addons.mozilla.org/en-US/themes/update-check/275698","version":"0"}

^ You will have to scroll past some text with basic information until you reach the "textcolor" and the "accentcolor" ones. The accentcolor (with the hex code after it) is the tab line color, while the textcolor should be obvious what it does.

Hex colors work kinda like the RGB ones, except writing a hashtag before the color numbers. The first 2 numbers belong to Red, the next 2 to Green, and the last 2 to Blue. 

So #0084ff would belong to a blueish light color (the higher the value, the more bright it is), which is the one that you can see over the active tab on the main UI picture I posted on the readme.

The only difference between hex colors and RGB ones, is that after 9 comes letters on hex colors. A being the min, F being the max.

Once you change the colors, you will have to restart firefox for the changes to take effect.

So... that should cover everything! 
I don't mind the questions, it might help others with the same issues, so don't worry about asking anything that you aren't too sure about!

**Comment by Icarus77** [comment]
Wow, thanks for all this useful info and taking the time to address all my questions! Will definitely be keeping this bookmarked for later use. 

Hope you have a good day and that lots of people find this neat theme.

**Comment by Izheil** [comment]
Thanks! enjoy the theme with the new changes. 

If you have any new question later on you can open a new issue, I'll mark this one as solved now.
