### ISSUE TITLE
No more dark scrollbar after Firefox update

### ISSUE THREAD

**Issue by BelladonnavGF** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#4]
Hi Izheil,

I see you're keeping at it, updating your code continuously. Let me be the one saying "THX for that"!

Now that the 1st Firefox "Quantum" updates have come and went, I noticed that the update "resets" the `chrome.manifest` file, which becomes 0 bytes again, because the added line
`override chrome://global/skin/scrollbars.css scrollbars.css`
is deleted.

Maybe it will be good to put this in your `README.md`, giving people a heads-up, and saving yourself a lot of work and open issues?

**Comment by Izheil** [comment]
Thanks for the information!

Yeah, I noticed it not long ago on a laptop where this happened, and I'm looking for some more permanent way to fix it. The only possible ways I found so far weren't too "good", requiring .bat files and changing shortcuts, so I've decided to look into extensions and see if I can pull together one for the scrollbars.

The problem with this is that webextensions aren't specially known for their UI changing support. Either way, I'll keep trying to find a permanent way to change them past firefox updates, so I'll keep this issue open until I find a better way. Either way, I'll update the readme with the information while I try to find the way, so again, thanks for taking the time to comment it!

**Comment by Izheil** [comment]
Well, after investigating webextensions APIs, I found that theming the scrollbars with overrides of the omni.ja files is (surprise surprise) impossible until new theming API features come along. 

Since we already kind of expected this, the only possible way to re-patch the scrollbars after each update automatically would be using some kind of file-watcher service... which would need to be running in the background all the time. As you can tell, this isn't quite an optimal solution, neither a one that I'd want to do (it would not consume many resources, but it would still be quite a hacky solution).

So, since our best bet is still wait for better webextensions APIs, I decided to at least make re-patching a bit easier with some batch files. Right now I've only posted the Windows re-patchers (on the scrollbars patches folder here), but I'll be looking into making Linux and Mac re-patchers as well in the next few days. 

With these, you'd only have to keep the bat file anywhere you wanted on your PC, and run it with admin privileges after a firefox update (thus updating the chrome.manifest). If for some reason you don't have firefox installed on the default paths commented on the readme in the patches folder... You'll have to edit the .bat with the updated path, of course.

I've also added a "first-time patch" for those that don't want to navigate into firefox's root folder. This first time patch will paste the scrollbars.css and overwrite the chrome.manifest, so it's only difference with the re-patchers is that it is also suposed to paste the scrollbars.css.

Of course I'll leave the old "do-it-yourself" instructions for those that do not trust .bat files.

I know it's not a solution, but at least it should mitigate the issue! (Hopefully, either with a stylus webextension update that allows "AGENT_SHEET", or webextensions theme API updates we will be able to theme the scrollbars directly sometime in the future without doing these improvised "fixes")

**Comment by BelladonnavGF** [comment]
I agree with you that it's difficult to anticipate all different install options people might have. I think personally that the "manual, copy-paste route" is indeed the best option, always giving full understanding and control of what you're doing, and for example taking into account different paths to `chrome.manifest`. But you're right: some would rather like something less manual, for what ever reason.
As for me (on Linux) a quick bash adds the code to `chrome.manifest` easily:

`echo 'override chrome://global/skin/scrollbars.css scrollbars.css' | sudo tee -a /usr/lib/firefox/browser/chrome.manifest`

... but then again, like you said, I don't know how "universal" that is. For example some on Linux install to `/opt/`, and Apple and mobiles paths probably are different again. And yes, of course it would be possible to expand, search for `chrome.manifest`, ask for user confirmation with each step before adding the code. Having said that, I understand that you would like to accommodate users with batches and stuff (kudos), but anticipating the already mentioned system variabilities, I think a good description (like you have now, kudos again) is perhaps just as helpful. Don't forget, if users did it one time, they know how to do it again without a sweat. Well, at least, I hope so ☺

**Comment by Izheil** [comment]
I tried to use the default installation paths that appear on some Mozilla pages as an example, but looks like they may be a bit outdated (at least for linux). 

As you said, explaining what's happening in each part of the process is important so that everyone knows what are they actually doing and why, and at least on that behalf, I think Linux users are probably more advanced than windows users on using commands like those and understanding what's happening. 

On that note, I'll try to get virtualbox and install linux to see if I can make an executable shell script for easier access with a more updated path. Of course I'll still leave the notes explaining what to run and how, just in case someone runs into some kind of problem. For those that have custom paths, they will have to either edit the script, or run the commands with the explanations given (they should only need to change the path, so.... yeah).

About Mac, I'll try to put it to the test as well and see how well the current shell script does and make changes if necessary.

I'll release more up-to-date versions tomorrow, or when I have some time to test it all properly.

As for mobiles... I'm not sure this method would even work, since they have other classes, etc... But since I'm not really a firefox mobile user, I guess that would be a job for another person).

Either way, thanks for taking the time to test it and giving examples! It helps a lot having feedback on the changes so that we can use it with as few problems as possible.

**Comment by Izheil** [comment]
So I recently found a new way to edit the scrollbars in a more permanent way without having to re-patch the chrome.manifest in [here](https://www.reddit.com/r/firefox/comments/7dtcpm/restyle_an_userstyle_manager_that_can_edit/).
I adapted the files a bit so that they show the scrollbar I had already modified here, so you can either copy the files from here or directly from the comment in reddit.

If you want to use the files found here, go to the new "Scrollbars dark theme" folder, and from there:
- Copy the contents of the "Root" folder found in this repository to Firefox root folder.
- Copy the contents of the "Profile" folder found in this repository to the chrome folder inside your profile folder.
- Open the <code>about:profiles</code> URL with firefox, and open the local profile folder there.
- Open the "startupcache" folder and delete everything there.

The only downside I can see is that since it uses JavaScript to change the CSS, it **could** have some slowdowns sometimes, but I haven't really seen any so far, so I'm going to stick with this new method and see how it goes.

I'll leave the old method just in case Mozilla decides to release a patch to completelly disallow userChrome.js, but at least it will be the most permanent way as of right now.
