### ISSUE TITLE
Synced Tabs portion of sidebar is not themed

### ISSUE THREAD

**Issue by demir-delic** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#6]
Hi @Izheil,

Thanks for putting this theme together. I've noticed that, while the Bookmarks and History portions of the sidebar look great, Synced Tabs retains its default look. Would you consider looking into applying the theme to Synced Tabs as well?

![synced-tabs](https://user-images.githubusercontent.com/17265830/36827019-397ac3b8-1cce-11e8-9522-fbbed0edcb52.png)

Thanks,
Demir

**Comment by Izheil** [comment]
Thanks for noting it!
I didn't theme it because that part of the browser can't be themed through userContent or userChrome, so when I first put the theme together I couldn't do much else. 
Gladly now we can theme it in the same way we theme the scrollbar or the tooltips, but that requires a bit more time and modding of your firefox. 

I've updated the repository with the required file for this, so now you only have to follow the method explained on the "scrollbars & tooltips" folder, and then make sure to place the recently uploaded "Sync-tabs-sidebar.uc.js" file inside your chrome folder.
