### ISSUE TITLE
Adding files to profile does nothing

### ISSUE THREAD

**Issue by eversins** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#7]
Hello, I have tried installing the color theme by copying userChrome.css and userContent.css to my user profile folder, but the theme is not applied.

I have tried it with FF57 and FF58-dev, to double check that I got the correct folder I even opened it in about:profiles, where the files are present.
They are located in "/home/user/.mozilla/firefox/sirgpbr9.dev-edition-default/"

Am I missing something? Thanks.

**Comment by Izheil** [comment]
You have to create a folder named "chrome" inside your profile folder, just putting those files inside the profile folder won't make it have any effect (I'm going to assume you meant you opened it through about:support instead of about:profiles, since that would take you to the wrong folder, but you gave the right location). 

The folder they should be inside would be:

<code>/home/user/.mozilla/firefox/sirgpbr9.dev-edition-default/chrome/</code>

I'll try to make it clearer on the installation section to avoid confusion for other people. 

Hope that helps!

**Comment by eversins** [comment]
Thank you that fixed it, sorry for wasting your time.

I have no clue how I missed it, I read the readme multiple times and did not catch that I had to create the chrome folder, I thought it might be a legacy folder..
