### ISSUE TITLE
Color of Context Menu's left edge not changing colors

### ISSUE THREAD

**Issue by Ludo91** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#9]
Hi!

I just started using the code and I noticed that the left edge of the context menus is still white:

![image](https://user-images.githubusercontent.com/38870554/39454726-461eb392-4cdd-11e8-81c6-fa36ba241a4d.png)

Same if I open anything from the Menu Bar:

![image](https://user-images.githubusercontent.com/38870554/39454758-72923be2-4cdd-11e8-87d9-7143c76f6140.png)

These are actually not very disturbing, but I have a lot of bookmarks, and if I click on the "Show more bookmarks" button, the whole list shows with white edges:

![image](https://user-images.githubusercontent.com/38870554/39454806-ab5791c0-4cdd-11e8-9262-fb579948d436.png)

Am I overlooking something in the code or someone else is experiencing the same issues?

**Comment by Izheil** [comment]
That issue doesn't seem to happen to me, so I'm a bit confused as of what could be causing it.
So... I'm going to need some more information to see if I can help.
Does it happen to ALL context menus? Including the bookmark bar folder context menus, or the web area context menus (where there is the option to save image, etc...)
Are you using just parts of the code? The issue could be caused because the menupopup selector has more padding than it should (Thing that shouldn't happen since it already has the -moz-appearance: none rule).
If this is the cause, try writing on bottom of your userchrome.css file the following rule:
<pre>
menupopup {
  padding: 0 !important}
</pre>
If the problem persists after you restart firefox after that change, try changing "padding" for "margin" and see if it still happens.

Does it happen with all lightweight themes, or just with the default firefox dark theme while using the code? The code works best with any other random lightweight theme (since it was designed to be used with those), even tho it still shouldn't happen with the default firefox dark theme.

If it still happens, we can try some other things, but first we should see what exactly is causing those white margins.

**Comment by Ludo91** [comment]
Thanks a lot for the prompt response Izhheil, the issue is resolved.

The above proposed solution ideas didn't work out, but as you mentioned this isn't how it should look like, I had a look in my userChrome.css, where among pieces of your code, other code was also included. So i checked it and found following piece which was responsible for the above described behaviour: 

`.arrowscrollbox-scrollbox {
  padding-inline-start: 10px !important;
}`

It was commented out and issue is resolved.
